### ISSUE TITLE
liionpack does not work on Python 3.7

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/liionpack#215]
### Discussed in https://github.com/pybamm-team/liionpack/discussions/214

<div type='discussions-op-text'>

<sup>Originally posted by **frivollier** January 14, 2023</sup>
I am looking for help with liionpack  https://github.com/pybamm-team/liionpack

I am getting the following type KeyError while running all examples.  (this is  error from  the example git home page readme.md)

`Traceback (most recent call last):
  File "/Users/frivollier/software_local/BESSTools1/liionpack_DT/test.py", line 46, in <module>
    manager='casadi')
  File "/Users/frivollier/software_local/BESSTools1/venv/lib/python3.7/site-packages/liionpack/solver_utils.py", line 441, in solve
    setup_only=False,
  File "/Users/frivollier/software_local/BESSTools1/venv/lib/python3.7/site-packages/liionpack/solvers.py", line 317, in solve
    self.protocol = lp.generate_protocol_from_experiment(experiment, flatten=True)
  File "/Users/frivollier/software_local/BESSTools1/venv/lib/python3.7/site-packages/liionpack/protocols.py", line 30, in generate_protocol_from_experiment
    typ = op["type"]
KeyError: 'type'
`
running on mac python 3.7

thanks for pointing me in the right direction for some help.

Regards,

Fred

</div>

**Comment by Saransh-cpp** [comment]
## Issue
liionpack supports Python 3.7, 3.8, and 3.9, but pybamm’s recent version only supports 3.8 and 3.9. Installing liionpack on Python 3.7 works, but it installs an older version of pybamm (a version that supports Python 3.7). This older version of pybamm is incompatible with liionpack’s latest version, which results in errors.

## Solution
Drop Python 3.7 support :slightly_smiling_face:

---

Creating a PR.
