### ISSUE TITLE
DFN model Run Time Error

### ISSUE THREAD

**Issue by ksnvikrant** [pybamm-team/liionpack#48]
I ran the example on liionpack by changing the Pybamm model from SPMe to DFN in 'simulations.py' file. 
In 'simulations.py', I changed create_simulation function.
I replaced line #50: model = pybamm.lithium_ion.SPMe(options = {"thermal": "lumped",}) to 
model = pybamm.lithium_ion.DFN(options = {"thermal": "lumped",})

I am getting a run time error as follows:

Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-19 09:06:28 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-19 09:06:28 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") […/casadi/core/map.cpp:449]
RuntimeError: .../casadi/core/function_internal.hpp:1229: Evaluation failed

**Comment by tinosulzer** [comment]
Not sure if this is related or if the error appears before, but the code to support a DAE solve (just as the DFN) is only half done in `_mapped_step`

**Comment by wigging** [comment]
I also get an error when the model is DFN. Below is the error with traceback message.

```
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Newton/Linesearch algorithm failed to converge.
CasADi - 2021-10-21 10:01:06 WARNING("Exception raised: Error in Function::operator() for 'map3_F' [Map] at .../casadi/core/function.cpp:1368:
Error in Function::operator() for 'F' [IdasInterface] at .../casadi/core/function.cpp:1368:
.../casadi/interfaces/sundials/idas_interface.cpp:591: IDACalcIC returned "IDA_CONV_FAIL". Consult IDAS documentation.") [.../casadi/core/map.cpp:449]
Solving Pack:   0%|                                                                                                 | 0/630 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/g72/Desktop/zzexample.py", line 32, in <module>
    output = lp.solve(netlist=netlist,
  File "/Users/g72/Desktop/ORNL/MegaPack/liionpack/liionpack/solver_utils.py", line 325, in solve
    step_solutions, var_eval = step_fn(sim.built_model, step_solutions,
  File "/Users/g72/Desktop/ORNL/MegaPack/liionpack/liionpack/solver_utils.py", line 125, in _mapped_step
    casadi_sol = integrator(
  File "/opt/miniconda3/envs/lipack/lib/python3.9/site-packages/casadi/casadi.py", line 13453, in __call__
    return self.call(kwargs)
  File "/opt/miniconda3/envs/lipack/lib/python3.9/site-packages/casadi/casadi.py", line 12324, in call
    return _casadi.Function_call(self, *args)
RuntimeError: .../casadi/core/function_internal.hpp:1229: Evaluation failed
```

**Comment by TomTranter** [comment]
The code to run a DFN model is now in the solver classes #69 but they will not actually run it because a simulation is created behind the scenes and the model is determined there. Need to think about what PyBaMM objects are best controlled by the users and what are best controlled by the liionpack solvers. I will create a new issue for this.
